AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Layout/LineLength:
  Max: 120

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Metrics/ClassLength:
  Exclude:
    - lib/deepl_diff/tokenizer.rb
